# Generated by Django 6.0.4 on 2026-05-02 17:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0002_customer_user_driver_user_userprofile'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Tariff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название тарифа')),
                ('base_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Базовая ставка, руб.')),
                ('price_per_km', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Цена за 1 км, руб.')),
                ('price_per_ton', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Цена за 1 тонну, руб.')),
                ('urgency_coefficient', models.DecimalField(decimal_places=2, default=1.0, max_digits=3, verbose_name='Коэффициент срочности')),
            ],
            options={
                'verbose_name': 'Тариф',
                'verbose_name_plural': 'Тарифы',
            },
        ),
        migrations.AddField(
            model_name='order',
            name='distance_km',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Расстояние, км'),
        ),
        migrations.AddField(
            model_name='order',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Стоимость, руб.'),
        ),
        migrations.CreateModel(
            name='OrderStatusHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('old_status', models.CharField(blank=True, choices=[('new', 'Новый'), ('assigned', 'Назначен'), ('in_transit', 'В пути'), ('completed', 'Выполнен'), ('cancelled', 'Отменён')], max_length=20, null=True, verbose_name='Предыдущий статус')),
                ('new_status', models.CharField(choices=[('new', 'Новый'), ('assigned', 'Назначен'), ('in_transit', 'В пути'), ('completed', 'Выполнен'), ('cancelled', 'Отменён')], max_length=20, verbose_name='Новый статус')),
                ('changed_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата изменения')),
                ('changed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Кем изменено')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_history', to='crm.order')),
            ],
            options={
                'verbose_name': 'История статуса',
                'verbose_name_plural': 'Истории статусов',
                'ordering': ['-changed_at'],
            },
        ),
        migrations.AddField(
            model_name='order',
            name='tariff',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='crm.tariff', verbose_name='Тариф'),
        ),
    ]
