# Generated by Django 6.0.1 on 2026-05-09 11:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0003_tariff_order_distance_km_order_price_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='delivery_lat',
            field=models.FloatField(blank=True, null=True, verbose_name='Широта доставки'),
        ),
        migrations.AddField(
            model_name='order',
            name='delivery_lon',
            field=models.FloatField(blank=True, null=True, verbose_name='Долгота доставки'),
        ),
        migrations.AddField(
            model_name='order',
            name='pickup_lat',
            field=models.FloatField(blank=True, null=True, verbose_name='Широта подачи'),
        ),
        migrations.AddField(
            model_name='order',
            name='pickup_lon',
            field=models.FloatField(blank=True, null=True, verbose_name='Долгота подачи'),
        ),
        migrations.AlterField(
            model_name='orderstatushistory',
            name='changed_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='orderstatushistory',
            name='changed_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='orderstatushistory',
            name='new_status',
            field=models.CharField(choices=[('new', 'Новый'), ('assigned', 'Назначен'), ('in_transit', 'В пути'), ('completed', 'Выполнен'), ('cancelled', 'Отменён')], max_length=20),
        ),
        migrations.AlterField(
            model_name='orderstatushistory',
            name='old_status',
            field=models.CharField(blank=True, choices=[('new', 'Новый'), ('assigned', 'Назначен'), ('in_transit', 'В пути'), ('completed', 'Выполнен'), ('cancelled', 'Отменён')], max_length=20, null=True),
        ),
    ]
