# Generated by Django 6.0.4 on 2026-05-29 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0004_order_delivery_lat_order_delivery_lon_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='driver',
            name='telegram_id',
            field=models.BigIntegerField(blank=True, null=True, verbose_name='Telegram ID'),
        ),
    ]
